import Link from "next/link";
import { ArrowRight, ArrowUpRight, GraduationCap, ShieldCheck, FileText, Puzzle, Check } from "lucide-react";
import { SchoolLogo } from "@/components/ui/school-logo";
import { Logo } from "@/components/ui/logo";
import { LearningArt } from "@/components/ui/learning-art";

const FEATURES = [
  { title: "Sigue tu curiosidad.", name: "Tutor IA", description: "Trabaja un tema con preguntas que guían tu pensamiento, una idea a la vez.", icon: GraduationCap },
  { title: "Hazlo tuyo.", name: "Desafíos", description: "Resuelve, explica e investiga. Pon tu comprensión en práctica y gana XP.", icon: Puzzle },
  { title: "Haz una mejor pregunta.", name: "Constructor de Prompts", description: "Construye un prompt útil y comprende las decisiones que lo hacen funcionar.", icon: FileText },
  { title: "Mira un poco más de cerca.", name: "Verificador de Datos", description: "Cuestiona las afirmaciones generadas por IA y descubre qué necesita verificación independiente.", icon: ShieldCheck },
];
export default function HomePage() {
  return <div className="min-h-screen bg-white">
    <header className="border-b border-card-border"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between gap-4 px-5 sm:px-10"><Logo /><nav aria-label="Navegación principal" className="hidden items-center gap-8 text-sm text-muted-foreground md:flex"><a href="#how-it-works" className="hover:text-primary">La experiencia</a><a href="#skills" className="hover:text-primary">Tu progreso</a><a href="#teachers" className="hover:text-primary">Para educadores</a></nav><div className="flex items-center gap-4"><Link href="/login" className="text-sm font-medium text-primary">Iniciar sesión</Link><Link href="/signup" className="hidden rounded-lg bg-primary px-4 py-2.5 text-sm font-medium text-white hover:bg-primary-hover sm:block">Comenzar<ArrowUpRight size={14} className="ml-2 inline" /></Link></div></div></header>
    <main>
      <section className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-16 sm:px-10 sm:py-24 lg:grid-cols-[1.1fr_1fr]">
        <div className="animate-fade-in-up"><SchoolLogo className="mb-7 max-w-[340px] !p-0" /><span className="eyebrow flex items-center gap-3"><span className="h-2 w-2 rounded-sm bg-ai" />Una nueva forma de aprender con IA</span><h1 className="mt-7 max-w-xl text-5xl font-semibold leading-[1.06] tracking-[-.055em] sm:text-6xl xl:text-7xl">Grandes ideas.<br />Mejores preguntas.<br /><span className="text-primary">Tu propia mente.</span></h1><p className="mt-7 max-w-md text-base leading-relaxed text-muted-foreground">Encuentra tu curiosidad con un poco de inteligencia. Construye comprensión real, practica nuevas habilidades y aprende a pensar de forma independiente con la IA.</p><div className="mt-9 flex flex-wrap items-center gap-6"><Link href="/signup" className="action-link">Comienza tu próximo capítulo<ArrowRight size={17} /></Link><a href="#how-it-works" className="text-link">Explora la experiencia<ArrowUpRight size={15} /></a></div><p className="mt-5 text-xs text-muted-foreground">Gratis para empezar. No se requiere tarjeta de crédito.</p></div>
        <div className="relative rounded-3xl border border-card-border bg-background p-5 sm:p-8">
          <div className="mb-5 flex items-center justify-between"><span className="eyebrow">Un momento de descubrimiento</span><span className="rounded-full bg-achievement-soft px-3 py-1 text-xs text-achievement-ink">Aprender, reinventado</span></div>
          <div className="panel overflow-hidden"><div className="border-b border-card-border px-6 py-4"><span className="ai-label">Tu compañero de pensamiento</span></div><div className="px-6 pt-6"><p className="text-xs text-muted-foreground">UNA PREGUNTA PUEDE CAMBIARLO TODO</p><h2 className="mt-3 text-2xl font-semibold leading-tight tracking-tight">¿Qué hace que una respuesta<br />merezca confianza?</h2></div><LearningArt /><div className="mx-5 mb-5 rounded-xl bg-background p-4"><p className="text-sm leading-relaxed">«Empecemos por la evidencia. ¿Cómo podrías verificar esta afirmación tú mismo?»</p><span className="mt-3 block text-xs font-medium text-ai">Tutor IA · Conversación de ejemplo</span></div></div>
          <div className="mt-5 flex items-center gap-3 text-xs text-muted-foreground"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-achievement"><Check size={14} className="text-foreground" /></span>Comprender se siente mejor que solo obtener la respuesta.</div>
        </div>
      </section>
      <section id="how-it-works" className="border-y border-card-border bg-background py-16 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-10"><div className="grid gap-5 md:grid-cols-2"><div><p className="eyebrow text-primary">Menos copiar. Más descubrir.</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Un conjunto de herramientas para<br />mentes independientes.</h2></div><p className="max-w-md self-end text-sm leading-relaxed text-muted-foreground">La IA puede darte una respuesta. MindForge te ayuda a comprenderla, cuestionarla y hacer algo con ella. Cada herramienta es una forma distinta de construir ese hábito.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{FEATURES.map((f,i) => <Link href="/signup" key={f.name} className="panel group p-6 hover:border-primary/30"><div className="flex items-center justify-between"><f.icon size={22} className={i === 0 ? "text-ai" : "text-primary"} /><span className="font-mono text-xs text-muted-foreground">0{i+1}</span></div><p className="eyebrow mt-9">{f.name}</p><h3 className="mt-3 text-lg font-semibold tracking-tight">{f.title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{f.description}</p><ArrowUpRight size={18} className="mt-6 text-primary transition-transform group-hover:translate-x-1" /></Link>)}</div></div></section>
      <section id="skills" className="mx-auto grid max-w-7xl gap-12 px-5 py-16 sm:px-10 sm:py-24 md:grid-cols-2"><div><p className="eyebrow text-primary">Pequeños pasos. Crecimiento real.</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Progreso que puedes ver.<br />Confianza que puedes sentir.</h2><p className="mt-5 max-w-md text-sm leading-relaxed text-muted-foreground">Observa cómo se desarrollan tus habilidades con la práctica. Gana experiencia, celebra los logros y construye una racha de aprendizaje, un intento independiente a la vez.</p><Link href="/signup" className="text-link mt-7">Construye tu mapa de habilidades<ArrowRight size={15} /></Link></div><div className="grid grid-cols-2 gap-x-8">{["Alfabetización en IA","Pensamiento crítico","Resolución de problemas","Investigación","Verificación","Independencia de la IA"].map((s,i) => <div key={s} className="border-b border-card-border py-5"><span className="font-mono text-xs text-primary">0{i+1}</span><h3 className="mt-3 text-sm font-semibold">{s}</h3></div>)}</div></section>
      <section id="teachers" className="mx-auto max-w-7xl px-5 pb-16 sm:px-10"><div className="grid gap-8 rounded-3xl bg-zinc-950 p-8 text-white sm:p-14 md:grid-cols-[1.3fr_1fr]"><div><p className="eyebrow !text-achievement">Para quienes inspiran el aprendizaje</p><h2 className="mt-5 text-3xl font-semibold tracking-tight sm:text-4xl">Una imagen más clara<br />de cada aula.</h2></div><div className="self-center"><p className="text-sm leading-relaxed text-white/75">Crea clases, invita a estudiantes con un código y observa su progreso de habilidades en conjunto. Encuentra las áreas que necesitan atención y ayuda a tus estudiantes a dar el siguiente paso.</p><Link href="/signup?role=teacher" className="mt-6 inline-flex items-center gap-3 rounded-lg bg-white px-5 py-3 text-sm font-semibold text-primary">Crea tu cuenta de docente<ArrowUpRight size={16} /></Link></div></div></section>
      <section className="px-5 pb-20 pt-7 text-center"><p className="eyebrow">Sigue siendo curioso</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Tu próximo «ya lo entiendo» empieza aquí.</h2><Link href="/signup" className="action-link mt-7">Empieza a aprender<ArrowRight size={16} /></Link></section>
    </main>
    <footer className="border-t border-card-border"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-6 px-5 py-8 sm:px-10"><Logo /><p className="text-xs text-muted-foreground">© 2026 MindForge. Una mente propia.</p><nav aria-label="Legal" className="flex gap-6 text-xs text-muted-foreground"><Link href="/privacy">Privacidad</Link><Link href="/terms">Términos</Link></nav></div></footer>
  </div>;
}
